package com.Nxer.TwistSpaceTechnology.common.material;

import static gregtech.api.enums.OrePrefixes.nanite;

import java.util.Arrays;

import goodgenerator.util.CharExchanger;
import gregtech.api.enums.Dyes;
import gregtech.api.enums.Element;
import gregtech.api.enums.Materials;
import gregtech.api.enums.MaterialBuilder;
import gregtech.api.enums.SubTag;
import gregtech.api.enums.TCAspects;
import gregtech.api.enums.TextureSet;
import gregtech.api.enums.TierEU;
import gregtech.common.render.items.InfinityRenderer;

/**
 * Register new material here by Gregtech Material System
 */
public class MaterialsTST {

    static final int offsetID = 260;
    // ID form 2242 ~ 2298 is available

    public static Materials loadNeutroniumAlloy() {
        return new MaterialBuilder().setName("Neutronium Alloy")
            .setDefaultLocalName("Neutronium Alloy")
            .setChemicalFormula("Nt\u2087Du\u2082Fl҉?")
            .setMetaItemSubID(offsetID)
            .setIconSet(TextureSet.SET_SHINY)
            .setTool().toolSpeed(32.0F)
            .setTool().toolDurability(98304000)
            .setTool().toolQualtiy(18)
            .setARGB(0x00d9dccb)
            .setMeltingPoint(12000)
            .setBlastFurnaceTemp(12500)
            .setBlastFurnaceRequired(true)
            .addOreItems()
            .addAspect(TCAspects.ORDO, 1)
            .addAspect(TCAspects.ALIENIS, 2)
            .addAspect(TCAspects.PERDITIO, 3)
            .addAspect(TCAspects.METALLUM, 5)
            .setAutoGeneratedBlastFurnaceRecipes(false)
            .setAutoGeneratedVacuumFreezerRecipe(false)
            .addCell()
            .addDustItems()
            .addMetalItems()
            .addGearItems()
            .constructMaterial();
            }
            
            

    public static Materials loadAxonisAlloy() {
        return new MaterialBuilder().setName("Axonis Alloy")
            .setDefaultLocalName("Axonis Alloy")
            .setChemicalFormula("۞\u2085(Hy⚶)\u2083⸎\u2082(IcMa)TbSh" + CharExchanger.shifter(9191))
            .setMetaItemSubID(offsetID + 1)
            .setIconSet(TextureSet.SET_SHINY)
            .setTool().setSpeed(96.0F)
            .setTool().setDurability(98304000)
            .setTool().setQuality(18)
            .setARGB(0x00c54324)
            .setMeltingPoint(13000)
            .setBlastFurnaceTemp(13200)
            .setBlastFurnaceRequired(true)
            .addAspect(TCAspects.SENSUS, 1)
            .addAspect(TCAspects.PRAECANTATIO, 2)
            .addAspect(TCAspects.METALLUM, 4)
            .setAutoGeneratedBlastFurnaceRecipes(false)
            .addCell()
            .addDustItems()
            .addMetalItems()
            .addGearItems()
            .contructMaterial();
    }
            

    public static Materials loadAxonium() {
        return new MaterialBuilder().setName("Axonium")
            .setDefaultLocalName("Axonium")
            .setChemiclFormula("A☀")
            .setMetaItemSubID(offsetID + 2)
            .setIconSet(TextureSet.SET_SHINY)
            .setTool().setSpeed(480.0F)
            .setTool().setDurablilty(1048576000)
            .setTool().setQualtiy(24)
            .setARGB(0x00f32d1b)
            .setMeltingPoint(23000)
            .setBlastFurnaceTemp(26000)
            .setBlastFurnaceRequired(true)
            .addAspect(TCAspects.SENSUS, 1)
            .addAspect(TCAspects.PRAECANTATIO, 2)
            .addAspect(TCAspects.VICTUS, 3)
            .addAspect(TCAspects.METALLUM, 5)
            .setAutoGeneratedBlastFurnaceRecipes(false)
            .setAutoGeneratedVacuumFreezerRecipe(false)
            .addPlamsa()
            .addCell()
            .addDustItems()
            .addMetalItems()
            .addGearItems()
            .constructMaterial();
    }

    public static Materials loadDubnium() {
        return new MaterialBuilder().setName("Dubnium")
            .setDefaultLocalName("Dubnium")
            .setElement(Element.Db)
            .setMetaItemSubID(offsetID + 3)
            .setIconSet(TextureSet.SET_METALLIC)
            .setTool().setQuality(2)
            .setARGB(0x00c8c8c8)
            .setMeltingPoint(3231)
            .addAspect(TCAspects.RADIO, 5)
            .addAspect(TCAspects.METALLUM, 3)
            .setAutoGeneratedBlastFurnaceRecipes(false)
            .setAutoGeneratedVacuumFreezerRecipe(false)
            .addPlasma()
            .addCell()
            .addDustItems()
            .addMetalItems()
            .constructMaterial();
    }

    // register Extra Information
    static {
        nanite.mGeneratedItems.add(Materials.CosmicNeutronium);
        nanite.mGeneratedItems.add(MaterialsTST.Axonium);
    }

    public static void initClient() {
        Axonium.renderer = new InfinityRenderer();
    }

    public static void init() {
        // to load this class~
    }

}
