package com.Nxer.TwistSpaceTechnology.recipe.machineRecipe.original;

import static com.dreammaster.item.NHItemList.HighEnergyFlowCircuit;
import static gregtech.api.enums.TierEU.RECIPE_LuV;
import static gregtech.api.enums.TierEU.RECIPE_UIV;

import com.Nxer.TwistSpaceTechnology.common.GTCMItemList;

import bartworks.API.recipe.BartWorksRecipeMaps;
import gregtech.api.enums.GTValues;
import gregtech.api.enums.ItemList;
import gregtech.api.enums.Materials;
import gregtech.api.enums.OrePrefixes;
import gregtech.api.interfaces.IRecipeMap;
import gregtech.api.recipe.RecipeMaps;
import gregtech.api.util.GTOreDictUnificator;
import gtPlusPlus.core.material.MaterialMisc;
import gtPlusPlus.core.material.MaterialsAlloy;
import tectech.thing.CustomItemList;

/**
 * NAC Recipe @see NACRecipePool
 */
public class CircuitAssemblerRecipePool {

    public static void loadRecipes() {
        final IRecipeMap CA = RecipeMaps.circuitAssemblerRecipes;
        final IRecipeMap CAL = BartWorksRecipeMaps.circuitAssemblyLineRecipes;

        // CAL now generated by enumeration, so both CA and CAL should be included
        // Optical Soc Circuit
        GTValues.RA.stdBuilder()
            .itemInputs(
                ItemList.Circuit_Board_Optical.get(6), // Normally 1, Sync with the CAL Nerf to 6x
                GTCMItemList.OpticalSOC.get(6),
                CustomItemList.DATApipe.get(6),
                GTOreDictUnificator.get(OrePrefixes.bolt, Materials.Infinity, 18))
            .fluidInputs(MaterialMisc.MUTATED_LIVING_SOLDER.getFluidStack(144 * 8))
            .itemOutputs(ItemList.Circuit_OpticalProcessor.get(1))
            .eut(RECIPE_UIV)
            .duration(20 * 60)
            .addTo(CA);

        GTValues.RA.stdBuilder()
            .itemInputs(
                ItemList.Wrap_OpticalCircuitBoards.get(1),
                GTCMItemList.OpticalSOC.get(16),
                CustomItemList.DATApipe.get(16),
                GTOreDictUnificator.get(OrePrefixes.bolt, Materials.Infinity, 48))
            .fluidInputs(MaterialMisc.MUTATED_LIVING_SOLDER.getFluidStack(144 * 2))
            .itemOutputs(ItemList.Circuit_OpticalProcessor.get(4)) // Normally 16, Sync with the NAC Nerf to 4
            .special(ItemList.CircuitImprint_OpticalProcessor.get(1))
            .eut(RECIPE_UIV)
            .duration(20 * 60 * 4)
            .addTo(CAL);

        // High Energy Flow Circuit
        GTValues.RA.stdBuilder()
            .itemInputs(
                ItemList.Circuit_Board_Multifiberglass_Elite.get(1),
                ItemList.Energy_LapotronicOrb2.get(1),
                ItemList.Circuit_Chip_QPIC.get(2),
                GTOreDictUnificator.get(OrePrefixes.wireFine, Materials.Infinity, 2))
            .fluidInputs(MaterialsAlloy.INDALLOY_140.getFluidStack(144 * 2))
            .itemOutputs(HighEnergyFlowCircuit.get(1))
            .eut(RECIPE_LuV)
            .duration(20 * 60)
            .addTo(CA);

        GTValues.RA.stdBuilder()
            .itemInputs(
                ItemList.Wrap_EliteCircuitBoards.get(1),
                ItemList.Energy_LapotronicOrb2.get(16),
                ItemList.Wrap_QuantumPowerICs.get(2),
                GTOreDictUnificator.get(OrePrefixes.wireFine, Materials.Infinity, 32))
            .fluidInputs(MaterialMisc.MUTATED_LIVING_SOLDER.getFluidStack(72))
            .itemOutputs(HighEnergyFlowCircuit.get(16))
            .special(ItemList.CircuitImprint_HighEnergyFlowCircuit.get(1))
            .eut(RECIPE_LuV)
            .duration(20 * 60 * 4)
            .addTo(CAL);
    }
}
