package com.Nxer.TwistSpaceTechnology.common.machine;

import static com.gtnewhorizon.structurelib.structure.StructureUtility.ofBlock;
import static com.gtnewhorizon.structurelib.structure.StructureUtility.ofBlockAnyMeta;
import static com.gtnewhorizon.structurelib.structure.StructureUtility.transpose;
import static gregtech.api.enums.GT_HatchElement.InputBus;
import static gregtech.api.enums.GT_HatchElement.InputHatch;
import static gregtech.api.enums.GT_HatchElement.OutputBus;
import static gregtech.api.enums.GT_HatchElement.OutputHatch;
import static gregtech.api.enums.Textures.BlockIcons.OVERLAY_DTPF_OFF;
import static gregtech.api.enums.Textures.BlockIcons.OVERLAY_DTPF_ON;
import static gregtech.api.enums.Textures.BlockIcons.OVERLAY_FUSION1_GLOW;

import net.minecraft.init.Blocks;
import net.minecraft.item.ItemStack;
import net.minecraftforge.common.util.ForgeDirection;

import com.Nxer.TwistSpaceTechnology.common.machine.multiMachineClasses.GTCM_MultiMachineBase;
import com.Nxer.TwistSpaceTechnology.util.TextLocalization;
import com.gtnewhorizon.structurelib.structure.IStructureDefinition;
import com.gtnewhorizon.structurelib.structure.ISurvivalBuildEnvironment;

import gregtech.api.GregTech_API;
import gregtech.api.enums.Textures;
import gregtech.api.interfaces.ITexture;
import gregtech.api.interfaces.metatileentity.IMetaTileEntity;
import gregtech.api.interfaces.tileentity.IGregTechTileEntity;
import gregtech.api.render.TextureFactory;
import gregtech.api.util.GT_HatchElementBuilder;
import gregtech.api.util.GT_Multiblock_Tooltip_Builder;

public class TST_EyeOfWood extends GTCM_MultiMachineBase<TST_EyeOfWood> {

    // region Class Constructor
    public TST_EyeOfWood(int aID, String aName, String aNameRegional) {
        super(aID, aName, aNameRegional);
    }

    public TST_EyeOfWood(String aName) {
        super(aName);
    }

    @Override
    public IMetaTileEntity newMetaEntity(IGregTechTileEntity aTileEntity) {
        return new TST_EyeOfWood(this.mName);
    }
    // endregion

    // region Processing Logic

    @Override
    public void onPostTick(IGregTechTileEntity aBaseMetaTileEntity, long aTick) {
        super.onPostTick(aBaseMetaTileEntity, aTick);
        if (aTick % 20 == 0) {

        }
    }

    // @NotNull
    // @Override
    // public CheckRecipeResult checkProcessing() {
    // setupProcessingLogic(processingLogic);
    //
    // CheckRecipeResult result = doCheckRecipe();
    // result = postCheckRecipe(result, processingLogic);
    // // inputs are consumed at this point
    // updateSlots();
    // if (!result.wasSuccessful()) return result;
    //
    // mEfficiency = (10000 - (getIdealStatus() - getRepairStatus()) * 1000);
    // mEfficiencyIncrease = 10000;
    // mMaxProgresstime = processingLogic.getDuration();
    // setEnergyUsage(processingLogic);
    //
    // mOutputItems = processingLogic.getOutputItems();
    // mOutputFluids = processingLogic.getOutputFluids();
    //
    // return result;
    // }

    @Override
    protected boolean isEnablePerfectOverclock() {
        return false;
    }

    @Override
    protected float getSpeedBonus() {
        return 0;
    }

    @Override
    protected int getMaxParallelRecipes() {
        return 0;
    }

    @Override
    public boolean checkMachine(IGregTechTileEntity aBaseMetaTileEntity, ItemStack aStack) {
        repairMachine();
        return checkPiece(STRUCTURE_PIECE_MAIN, horizontalOffSet, verticalOffSet, depthOffSet);
    }
    // endregion

    // region Structure
    // spotless:off
    private static final String STRUCTURE_PIECE_MAIN = "mainEyeOfWood";
    private final int horizontalOffSet = 16;
    private final int verticalOffSet = 16;
    private final int depthOffSet = 0;
    private static IStructureDefinition<TST_EyeOfWood> STRUCTURE_DEFINITION = null;
    @Override
    public void construct(ItemStack stackSize, boolean hintsOnly) {
        buildPiece(STRUCTURE_PIECE_MAIN, stackSize, hintsOnly, horizontalOffSet, verticalOffSet, depthOffSet);
    }
    @Override
    public int survivalConstruct(ItemStack stackSize, int elementBudget, ISurvivalBuildEnvironment env) {
        if (mMachine) return -1;
        return survivialBuildPiece(STRUCTURE_PIECE_MAIN, stackSize, horizontalOffSet, verticalOffSet, depthOffSet, elementBudget, env, false, true);
    }
/*
A -> ofBlock...(gt.blockcasings, 10, ...); // hatches
B -> ofBlock...(tile.blockLapis, 0, ...);
C -> ofBlock...(tile.bookshelf, 0, ...);
D -> ofBlock...(tile.brick, 0, ...);
E -> ofBlock...(tile.stonebricksmooth, 3, ...);
F -> ofBlock...(tile.wood, 0, ...);
 */
    @Override
    public IStructureDefinition<TST_EyeOfWood> getStructureDefinition() {
        if (STRUCTURE_DEFINITION == null) {
            STRUCTURE_DEFINITION =
                IStructureDefinition
                    .<TST_EyeOfWood>builder()
                    .addShape(
                        STRUCTURE_PIECE_MAIN,
                        transpose(new String[][]{
                            {"                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","               D D               ","               D D               ","               D D               ","            DDDDDDDDD            ","               D D               ","            DDDDDDDDD            ","               D D               ","               D D               ","               D D               ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 "},
                            {"                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","               D D               ","               D D               ","               D D               ","               D D               ","              FFFFF              ","             FFDFDFF             ","         DDDDFDDFDDFDDDD         ","             FFFFFFF             ","         DDDDFDDFDDFDDDD         ","             FFDFDFF             ","              FFFFF              ","               D D               ","               D D               ","               D D               ","               D D               ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 "},
                            {"                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","               D D               ","               D D               ","               D D               ","                F                ","                F                ","             FFFFFFF             ","            FF     FF            ","            F  BBB  F            ","       DDD  F BCCCB F  DDD       ","          FFF BCCCB FFF          ","       DDD  F BCCCB F  DDD       ","            F  BBB  F            ","            FF     FF            ","             FFFFFFF             ","                F                ","                F                ","               D D               ","               D D               ","               D D               ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 "},
                            {"                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","               D D               ","               D D               ","                F                ","                F                ","                                 ","                                 ","                                 ","                                 ","                                 ","      DD                 DD      ","        FF             FF        ","      DD                 DD      ","                                 ","                                 ","                                 ","                                 ","                                 ","                F                ","                F                ","               D D               ","               D D               ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 "},
                            {"                                 ","                                 ","                                 ","                                 ","                                 ","               D D               ","              DDDDD              ","                F                ","                C                ","                C                ","                                 ","                                 ","                                 ","                                 ","      D                   D      ","     DD                   DD     ","      DFCC             CCFD      ","     DD                   DD     ","      D                   D      ","                                 ","                                 ","                                 ","                                 ","                C                ","                C                ","                F                ","              DDDDD              ","               D D               ","                                 ","                                 ","                                 ","                                 ","                                 "},
                            {"                                 ","                                 ","                                 ","                                 ","               D D               ","               D D               ","                F                ","             EBBCBBE             ","                                 ","                                 ","                                 ","                                 ","                                 ","       E                 E       ","       B                 B       ","    DD B                 B DD    ","      FC                 CF      ","    DD B                 B DD    ","       B                 B       ","       E                 E       ","                                 ","                                 ","                                 ","                                 ","                                 ","             EBBCBBE             ","                F                ","               D D               ","               D D               ","                                 ","                                 ","                                 ","                                 "},
                            {"                                 ","                                 ","                                 ","               D D               ","              DDDDD              ","                F                ","                C                ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","    D                       D    ","   DD                       DD   ","    DFC                   CFD    ","   DD                       DD   ","    D                       D    ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                C                ","                F                ","              DDDDD              ","               D D               ","                                 ","                                 ","                                 "},
                            {"                                 ","                                 ","               D D               ","               D D               ","                F                ","             EBBCBBE             ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","     E                     E     ","     B                     B     ","  DD B                     B DD  ","    FC                     CF    ","  DD B                     B DD  ","     B                     B     ","     E                     E     ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","             EBBCBBE             ","                F                ","               D D               ","               D D               ","                                 ","                                 "},
                            {"                                 ","                                 ","               D D               ","                F                ","                C                ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","  D                           D  ","   FC                       CF   ","  D                           D  ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                C                ","                F                ","               D D               ","                                 ","                                 "},
                            {"                                 ","               D D               ","               D D               ","                F                ","                C                ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 "," DD                           DD ","   FC                       CF   "," DD                           DD ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                C                ","                F                ","               D D               ","               D D               ","                                 "},
                            {"                                 ","               D D               ","                F                ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 "," D                             D ","  F                           F  "," D                             D ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                F                ","               D D               ","                                 "},
                            {"                                 ","               D D               ","                F                ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 "," D                             D ","  F                           F  "," D                             D ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                F                ","               D D               ","                                 "},
                            {"             DDDDDDD             ","               D D               ","             FFFFFFF             ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","  F                           F  ","  F                           F  ","DDF                           FDD","  F                           F  ","DDF                           FDD","  F                           F  ","  F                           F  ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","             FFFFFFF             ","               D D               ","               D D               "},
                            {"            DDAAAAADD            ","              FFFFF              ","            FF     FF            ","                                 ","                                 ","       E                 E       ","                                 ","     E                     E     ","                                 ","                                 ","                                 ","                                 ","  F                           F  ","  F                           F  "," F                             F ","DF                             FD"," F                             F ","DF                             FD"," F                             F ","  F                           F  ","  F                           F  ","                                 ","                                 ","                                 ","                                 ","     E                     E     ","                                 ","       E                 E       ","                                 ","                                 ","            FF     FF            ","              FFFFF              ","               D D               "},
                            {"            DAAAAAAAD            ","             FFDFDFF             ","            F  BBB  F            ","                                 ","      D                   D      ","       B                 B       ","    D                       D    ","     B                     B     ","                                 ","                                 ","                                 ","                                 ","  F                           F  "," F                             F "," F                             F ","DDB                           BDD"," FB                           BF ","DDB                           BDD"," F                             F "," F                             F ","  F                           F  ","                                 ","                                 ","                                 ","                                 ","     B                     B     ","    D                       D    ","       B                 B       ","      D                   D      ","                                 ","            F  BBB  F            ","             FFDFDFF             ","               D D               "},
                            {"            DAADDDAAD            ","         DDDDFDDFDDFDDDD         ","       DDD  F BCCCB F  DDD       ","      DD                 DD      ","     DD                   DD     ","    DD B                 B DD    ","   DD                       DD   ","  DD B                     B DD  ","  D                           D  "," DD                           DD "," D                             D "," D                             D ","DDF                           FDD","DF                             FD","DDB                           BDD","DDC                           CDD","DFC                           CFD","DDC                           CDD","DDB                           BDD","DF                             FD","DDF                           FDD"," D                             D "," D                             D "," DD                           DD ","  D                           D  ","  DD B                     B DD  ","   DD                       DD   ","    DD B                 B DD    ","     DD                   DD     ","      DD                 DD      ","       DDD  F BCCCB F  DDD       ","         DDDDFDDFDDFDDDD         ","            DDDDDDDDD            "},
                            {"            DAAD~DAAD            ","             FFFFFFF             ","          FFF BCCCB FFF          ","        FF             FF        ","      DFCC             CCFD      ","      FC                 CF      ","    DFC                   CFD    ","    FC                     CF    ","   FC                       CF   ","   FC                       CF   ","  F                           F  ","  F                           F  ","  F                           F  "," F                             F "," FB                           BF ","DFC                           CFD"," FC                           CF ","DFC                           CFD"," FB                           BF "," F                             F ","  F                           F  ","  F                           F  ","  F                           F  ","   FC                       CF   ","   FC                       CF   ","    FC                     CF    ","    DFC                   CFD    ","      FC                 CF      ","      DFCC             CCFD      ","        FF             FF        ","          FFF BCCCB FFF          ","             FFFFFFF             ","               D D               "},
                            {"            DAADDDAAD            ","         DDDDFDDFDDFDDDD         ","       DDD  F BCCCB F  DDD       ","      DD                 DD      ","     DD                   DD     ","    DD B                 B DD    ","   DD                       DD   ","  DD B                     B DD  ","  D                           D  "," DD                           DD "," D                             D "," D                             D ","DDF                           FDD","DF                             FD","DDB                           BDD","DDC                           CDD","DFC                           CFD","DDC                           CDD","DDB                           BDD","DF                             FD","DDF                           FDD"," D                             D "," D                             D "," DD                           DD ","  D                           D  ","  DD B                     B DD  ","   DD                       DD   ","    DD B                 B DD    ","     DD                   DD     ","      DD                 DD      ","       DDD  F BCCCB F  DDD       ","         DDDDFDDFDDFDDDD         ","            DDDDDDDDD            "},
                            {"            DAAAAAAAD            ","             FFDFDFF             ","            F  BBB  F            ","                                 ","      D                   D      ","       B                 B       ","    D                       D    ","     B                     B     ","                                 ","                                 ","                                 ","                                 ","  F                           F  "," F                             F "," F                             F ","DDB                           BDD"," FB                           BF ","DDB                           BDD"," F                             F "," F                             F ","  F                           F  ","                                 ","                                 ","                                 ","                                 ","     B                     B     ","    D                       D    ","       B                 B       ","      D                   D      ","                                 ","            F  BBB  F            ","             FFDFDFF             ","               D D               "},
                            {"            DDAAAAADD            ","              FFFFF              ","            FF     FF            ","                                 ","                                 ","       E                 E       ","                                 ","     E                     E     ","                                 ","                                 ","                                 ","                                 ","  F                           F  ","  F                           F  "," F                             F ","DF                             FD"," F                             F ","DF                             FD"," F                             F ","  F                           F  ","  F                           F  ","                                 ","                                 ","                                 ","                                 ","     E                     E     ","                                 ","       E                 E       ","                                 ","                                 ","            FF     FF            ","              FFFFF              ","               D D               "},
                            {"             DDDDDDD             ","               D D               ","             FFFFFFF             ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","  F                           F  ","  F                           F  ","DDF                           FDD","  F                           F  ","DDF                           FDD","  F                           F  ","  F                           F  ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","             FFFFFFF             ","               D D               ","               D D               "},
                            {"                                 ","               D D               ","                F                ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 "," D                             D ","  F                           F  "," D                             D ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                F                ","               D D               ","                                 "},
                            {"                                 ","               D D               ","                F                ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 "," D                             D ","  F                           F  "," D                             D ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                F                ","               D D               ","                                 "},
                            {"                                 ","               D D               ","               D D               ","                F                ","                C                ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 "," DD                           DD ","   FC                       CF   "," DD                           DD ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                C                ","                F                ","               D D               ","               D D               ","                                 "},
                            {"                                 ","                                 ","               D D               ","                F                ","                C                ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","  D                           D  ","   FC                       CF   ","  D                           D  ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                C                ","                F                ","               D D               ","                                 ","                                 "},
                            {"                                 ","                                 ","               D D               ","               D D               ","                F                ","             EBBCBBE             ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","     E                     E     ","     B                     B     ","  DD B                     B DD  ","    FC                     CF    ","  DD B                     B DD  ","     B                     B     ","     E                     E     ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","             EBBCBBE             ","                F                ","               D D               ","               D D               ","                                 ","                                 "},
                            {"                                 ","                                 ","                                 ","               D D               ","              DDDDD              ","                F                ","                C                ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","    D                       D    ","   DD                       DD   ","    DFC                   CFD    ","   DD                       DD   ","    D                       D    ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                C                ","                F                ","              DDDDD              ","               D D               ","                                 ","                                 ","                                 "},
                            {"                                 ","                                 ","                                 ","                                 ","               D D               ","               D D               ","                F                ","             EBBCBBE             ","                                 ","                                 ","                                 ","                                 ","                                 ","       E                 E       ","       B                 B       ","    DD B                 B DD    ","      FC                 CF      ","    DD B                 B DD    ","       B                 B       ","       E                 E       ","                                 ","                                 ","                                 ","                                 ","                                 ","             EBBCBBE             ","                F                ","               D D               ","               D D               ","                                 ","                                 ","                                 ","                                 "},
                            {"                                 ","                                 ","                                 ","                                 ","                                 ","               D D               ","              DDDDD              ","                F                ","                C                ","                C                ","                                 ","                                 ","                                 ","                                 ","      D                   D      ","     DD                   DD     ","      DFCC             CCFD      ","     DD                   DD     ","      D                   D      ","                                 ","                                 ","                                 ","                                 ","                C                ","                C                ","                F                ","              DDDDD              ","               D D               ","                                 ","                                 ","                                 ","                                 ","                                 "},
                            {"                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","               D D               ","               D D               ","                F                ","                F                ","                                 ","                                 ","                                 ","                                 ","                                 ","      DD                 DD      ","        FF             FF        ","      DD                 DD      ","                                 ","                                 ","                                 ","                                 ","                                 ","                F                ","                F                ","               D D               ","               D D               ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 "},
                            {"                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","               D D               ","               D D               ","               D D               ","                F                ","                F                ","             FFFFFFF             ","            FF     FF            ","            F  BBB  F            ","       DDD  F BCCCB F  DDD       ","          FFF BCCCB FFF          ","       DDD  F BCCCB F  DDD       ","            F  BBB  F            ","            FF     FF            ","             FFFFFFF             ","                F                ","                F                ","               D D               ","               D D               ","               D D               ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 "},
                            {"                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","               D D               ","               D D               ","               D D               ","               D D               ","              FFFFF              ","             FFDFDFF             ","         DDDDFDDFDDFDDDD         ","             FFFFFFF             ","         DDDDFDDFDDFDDDD         ","             FFDFDFF             ","              FFFFF              ","               D D               ","               D D               ","               D D               ","               D D               ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 "},
                            {"                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","               D D               ","               D D               ","               D D               ","            DDDDDDDDD            ","               D D               ","            DDDDDDDDD            ","               D D               ","               D D               ","               D D               ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 "}
                        })
                    )
                    .addElement(
                        'A',
                        GT_HatchElementBuilder
                            .<TST_EyeOfWood>builder()
                            .atLeast(InputBus, OutputBus, InputHatch, OutputHatch)
                            .adder(TST_EyeOfWood::addToMachineList)
                            .dot(1)
                            .casingIndex(10)
                            .buildAndChain(GregTech_API.sBlockCasings1, 10))
                    .addElement('B', ofBlock(Blocks.lapis_block, 0))
                    .addElement('C', ofBlock(Blocks.bookshelf, 0))
                    .addElement('D', ofBlock(Blocks.brick_block, 0))
                    .addElement('E', ofBlock(Blocks.stonebrick, 3))
                    .addElement('F', ofBlockAnyMeta(Blocks.planks))
                    .build();
        }
        return STRUCTURE_DEFINITION;
    }
    // spotless:on
    // endregion

    // region General

    @Override
    protected GT_Multiblock_Tooltip_Builder createTooltip() {
        final GT_Multiblock_Tooltip_Builder tt = new GT_Multiblock_Tooltip_Builder();
        tt.addMachineType(TextLocalization.Tooltip_EyeOfWood_MachineType)
            .addInfo(TextLocalization.Tooltip_EyeOfWood_Controller)
            .addInfo(TextLocalization.Tooltip_EyeOfWood_01)
            .addInfo(TextLocalization.StructureTooComplex)
            .addInfo(TextLocalization.BLUE_PRINT_INFO)
            .addSeparator()
            .beginStructureBlock(33, 33, 33, false)
            .addController(TextLocalization.textFrontCenter)
            .addInputBus(TextLocalization.textAnyCasing, 2)
            .addOutputBus(TextLocalization.textAnyCasing, 2)
            .toolTipFinisher(TextLocalization.ModName);
        return tt;
    }

    @Override
    public ITexture[] getTexture(IGregTechTileEntity aBaseMetaTileEntity, ForgeDirection side, ForgeDirection aFacing,
        int colorIndex, boolean aActive, boolean redstoneLevel) {
        if (side == aFacing) {
            if (aActive) {
                return new ITexture[] { Textures.BlockIcons.getCasingTextureForId(10), TextureFactory.builder()
                    .addIcon(OVERLAY_DTPF_ON)
                    .extFacing()
                    .build(),
                    TextureFactory.builder()
                        .addIcon(OVERLAY_FUSION1_GLOW)
                        .extFacing()
                        .glow()
                        .build() };
            }

            return new ITexture[] { Textures.BlockIcons.getCasingTextureForId(10), TextureFactory.builder()
                .addIcon(OVERLAY_DTPF_OFF)
                .extFacing()
                .build() };
        }

        return new ITexture[] { Textures.BlockIcons.getCasingTextureForId(10) };
    }
}
