
name: Build and test

on:
  pull_request:
    branches: [ master, main, release/* ]
  push:
    branches: [ master, main, release/* ]

jobs:
  build-and-test:
    uses: GTNewHorizons/GTNH-Actions-Workflows/.github/workflows/build-and-test.yml@master
    secrets: inherit
    with:
      timeout: 900
